In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [36]:
df=pd.read_csv('/content/drive/My Drive/data_science_workshop/test_data.csv',index_col='sample_name')
df.head()

NameError: ignored

In [37]:
df.head()

NameError: ignored

In [ ]:
df['column2']

sample_name
sample1    0.25
sample2     0.9
sample3    0.43
sample4    c084
Name: column2, dtype: object

In [ ]:
df1=df[['column2','column4']]
df1.head()

            column2  column4
sample_name
sample1        0.25     0.00
sample2         0.9     0.75
sample3        0.43     0.02
sample4        c084     0.90

In [ ]:
df['column34']=df['column3']+df['column4']
df.head()

             column0 column1 column2  column3  column4  column34
sample_name
sample1      control     yes    0.25     0.10     0.00      0.10
sample2         case     yes     0.9     0.25     0.75      1.00
sample3      control     yes    0.43     0.23     0.02      0.25
sample4         case      no    c084     0.34     0.90      1.24

In [ ]:
df['column01']=df['column0']+"_"+df['column1']
df.head()

             column0 column1 column2  column3  column4  column34     column01
sample_name
sample1      control     yes    0.25     0.10     0.00      0.10  control_yes
sample2         case     yes     0.9     0.25     0.75      1.00     case_yes
sample3      control     yes    0.43     0.23     0.02      0.25  control_yes
sample4         case      no    c084     0.34     0.90      1.24      case_no

In [ ]:
df.loc[df['column0']=='control','new_column0']=10
df.loc[df['column0']=='case','new_column0']=9
df.head()

In [ ]:
df.loc[df['column0']=='control']